#!/bin/bash

# Test de Persistencia y Restauración de Filtros - IMMER
# Script para verificar que la persistencia funciona correctamente

echo "🧪 Test: Persistencia y Restauración de Filtros"
echo "=============================================="
echo ""

echo "📋 Instrucciones de prueba paso a paso:"
echo ""

echo "🔍 PASO 1: Verificar estado inicial"
echo "1. Abrir http://localhost:5173/shop"
echo "2. Abrir DevTools (F12) → Console"
echo "3. Ejecutar: window.debugImmerCatalog.debugLocalStorage()"
echo "4. Verificar que NO hay filtros guardados o están vacíos"
echo ""

echo "💾 PASO 2: Crear estado para persistir"
echo "1. En la página /shop, aplicar filtros:"
echo "   - Buscar texto: 'bujia'"
echo "   - Seleccionar marca: 'NGK'"
echo "   - Seleccionar grupo: algún grupo disponible"
echo "   - Navegar a página 3 o 4"
echo "2. Verificar que aparecen productos filtrados"
echo "3. En console: window.debugImmerCatalog.forcePersistCurrentState()"
echo "4. En console: window.debugImmerCatalog.debugLocalStorage()"
echo "5. ✅ VERIFICAR: Los filtros se guardaron correctamente"
echo ""

echo "🔄 PASO 3: Simular navegación"
echo "1. Navegar a /cart (agregar cualquier producto)"
echo "2. Desde el carrito, hacer clic en 'Seguir Comprando' o navegar a /shop"
echo "3. ✅ VERIFICAR: Los filtros y paginación se restauran automáticamente"
echo "4. ✅ VERIFICAR: La página actual es la misma que antes (3 o 4)"
echo "5. ✅ VERIFICAR: Los productos mostrados coinciden con los filtros"
echo ""

echo "🧪 PASO 4: Verificación manual adicional"
echo "1. En console: window.debugImmerCatalog.debugLocalStorage()"
echo "2. ✅ VERIFICAR: timestamp reciente en los filtros guardados"
echo "3. ✅ VERIFICAR: currentPage coincide con la página mostrada"
echo "4. ✅ VERIFICAR: selectedBrand, selectedGroup no son null"
echo "5. En console: window.debugImmerCatalog.checkCurrentState()"
echo "6. ✅ VERIFICAR: stores actuales coinciden con localStorage"
echo ""

echo "🐛 PASO 5: Debug de problemas"
echo "Si la restauración no funciona:"
echo "1. En console: window.debugImmerCatalog.debugLocalStorage()"
echo "2. Verificar si hay datos en localStorage.lastCatalogFilters"
echo "3. Verificar que timestamp no sea muy antiguo (< 30 min)"
echo "4. En console: window.debugImmerCatalog.restoreCatalogState()"
echo "5. Revisar logs de consola para ver dónde falla"
echo ""

echo "🔧 PASO 6: Limpiar y reiniciar"
echo "1. En console: window.debugImmerCatalog.clearCatalogState()"
echo "2. Recargar página (F5)"
echo "3. Repetir desde PASO 1"
echo ""

echo "📊 Puntos críticos a verificar:"
echo "- ✅ persistFiltersToStorage() se llama al cambiar filtros (con debounce 300ms)"
echo "- ✅ localStorage contiene datos válidos después de cambios"
echo "- ✅ persistFiltersImmediately() se llama después de búsquedas exitosas"
echo "- ✅ markNavigationFromShop() persiste antes de navegar al cart/profile"
echo "- ✅ handleBackToShop() marca navegación de regreso desde cart"
echo "- ✅ restoreCatalogState() encuentra y lee datos guardados"
echo "- ✅ Filtros y paginación se restauran visualmente"
echo "- ✅ Búsqueda se ejecuta con filtros restaurados"
echo ""

echo "🚀 Para ejecutar:"
echo "1. cd /home/pvalarezo/grisbi-apps/immer_web"
echo "2. npm run dev"
echo "3. Seguir pasos anteriores"
echo ""

echo "📁 Archivos relacionados:"
echo "- src/lib/stores/store.ts (persistencia automática con debounce)"
echo "- src/lib/util/util.ts (restauración, debug y persistencia inmediata)"
echo "- src/routes/shop/+page.svelte (activación de restauración)"
echo "- src/lib/components/SimpleCart.svelte (persistencia al ir al carrito)"
echo "- src/routes/cart/+page.svelte (marcado de regreso al shop)"
echo "- src/lib/components/UserNavbar.svelte (persistencia al ir al perfil)"
