#!/bin/bash

# Script de Pruebas - Navegación Persistente
# Para ejecutar después de iniciar el servidor de desarrollo

echo "🧪 GUÍA DE PRUEBAS MANUALES - NAVEGACIÓN PERSISTENTE"
echo "=================================================="
echo ""
echo "🌐 Servidor ejecutándose en: http://localhost:5173/"
echo ""
echo "📋 PASOS DE PRUEBA:"
echo ""
echo "1️⃣  PRUEBA BÁSICA DE PAGINACIÓN:"
echo "   • Abrir http://localhost:5173/shop"
echo "   • Aplicar un filtro (ej: texto 'bujia')"
echo "   • Ir a página 2 o 3 (usar botón 'Cargar más')"
echo "   • Verificar que aparece 'Página: 3 / X' en la UI"
echo "   • Hacer scroll hacia abajo"
echo "   • Click en carrito (esquina superior derecha)"
echo "   • Click en 'Tienda' para regresar"
echo "   • ✅ Verificar que se mantiene:"
echo "     - Filtro aplicado"
echo "     - Página: 3 / X (debe mostrar página 3)"
echo "     - Productos cargados de páginas 1, 2 y 3"
echo "     - Scroll restaurado"
echo ""
echo "2️⃣  PRUEBA MÚLTIPLES FILTROS:"
echo "   • En /shop aplicar:"
echo "     - Texto: 'bujia'"
echo "     - Marca: 'NGK'"
echo "     - Grupo: cualquier grupo"
echo "   • Cargar más páginas"
echo "   • Ir a /profile"
echo "   • Regresar a /shop"
echo "   • ✅ Verificar que todos los filtros se mantienen"
echo ""
echo "3️⃣  PRUEBA DE EXPIRACIÓN:"
echo "   • Navegar en /shop"
echo "   • Cambiar TTL en store.ts a 1 minuto"
echo "   • Esperar 2 minutos"
echo "   • Ir a otra página y regresar"
echo "   • ✅ Verificar que NO restaura (nueva búsqueda)"
echo ""
echo "4️⃣  PRUEBA NAVEGACIÓN EXTERNA:"
echo "   • Navegar en /shop"
echo "   • Abrir nueva pestaña con Google"
echo "   • Desde Google, ir a localhost:5173/shop"
echo "   • ✅ Verificar que NO restaura (nueva búsqueda)"
echo ""
echo "🔍 DEBUG ESPECÍFICO PARA PAGINACIÓN:"
echo "   • En Console, ejecutar:"
echo "     - checkCurrentState() // Ver estado actual"
echo "     - testPaginationRestore() // Probar restauración"
echo "   • Verificar logs específicos:"
echo "     - 'Final currentPage setting: X (was: Y)'"
echo "     - 'Final pagination state:'"
echo "     - '� Current App State:'"
echo ""
echo "❌ SI HAY ERRORES:"
echo "   • Buscar mensajes de error en consola"
echo "   • Verificar si aparece: 'Cannot read properties of null'"
echo "   • Revisar los logs de '🐛 Debug App State' para ver el estado"
echo "   • Reportar el contexto completo del error"
echo ""
echo "💾 VERIFICAR STORAGE:"
echo "   • DevTools → Application → Storage"
echo "   • localStorage: buscar 'lastCatalogFilters'"
echo "   • sessionStorage: buscar 'navigatedFromShop'"
echo ""
echo "⚠️  PROBLEMAS CONOCIDOS A OBSERVAR:"
echo "   • Filtros dependientes no se actualizan automáticamente"
echo "   • Carga lenta si hay muchas páginas (10+)"
echo "   • Posibles race conditions en conexiones lentas"
echo ""
echo "🎯 CRITERIOS DE ÉXITO:"
echo "   ✅ Filtros se mantienen tras navegar"
echo "   ✅ Paginación se restaura correctamente"
echo "   ✅ Scroll se restaura con smooth behavior"
echo "   ✅ Indicador 'Estado de navegación restaurado' aparece"
echo "   ✅ No restaura en navegación externa o estado expirado"
echo ""
echo "📋 REPORTAR ISSUES EN:"
echo "   /docs/DIAGNOSTICO_NAVEGACION.md"
echo ""
echo "=================================================="
